import React from 'react';
import {
  Utensils,
  Car,
  ShoppingBag,
  GraduationCap,
  Film,
  Receipt,
  HeartPulse,
  Plane,
  Tv,
  MoreHorizontal,
  Briefcase,
  Laptop,
  TrendingUp,
  Wallet,
  PlusCircle,
  Coffee,
  Book,
  Home,
  Smartphone,
  Gift,
  PiggyBank,
  Fuel,
  Bus,
  Tag,
  CreditCard,
  Building,
  Sparkles,
  ShoppingBasket,
  Smile,
  LucideProps,
} from 'lucide-react';

export const ICON_OPTIONS: { name: string; label: string; component: React.ComponentType<LucideProps> }[] = [
  { name: 'Utensils', label: 'Food & Dining', component: Utensils },
  { name: 'Coffee', label: 'Coffee & Drinks', component: Coffee },
  { name: 'ShoppingBasket', label: 'Groceries', component: ShoppingBasket },
  { name: 'Car', label: 'Transport / Fuel', component: Car },
  { name: 'Bus', label: 'Public Transit', component: Bus },
  { name: 'Fuel', label: 'Fuel / Gas', component: Fuel },
  { name: 'ShoppingBag', label: 'Shopping', component: ShoppingBag },
  { name: 'GraduationCap', label: 'Education', component: GraduationCap },
  { name: 'Book', label: 'Books & Studies', component: Book },
  { name: 'Film', label: 'Entertainment', component: Film },
  { name: 'Tv', label: 'Subscriptions', component: Tv },
  { name: 'Receipt', label: 'Bills & Utilities', component: Receipt },
  { name: 'Home', label: 'Housing & Rent', component: Home },
  { name: 'HeartPulse', label: 'Health & Medical', component: HeartPulse },
  { name: 'Plane', label: 'Travel & Trips', component: Plane },
  { name: 'Briefcase', label: 'Salary / Work', component: Briefcase },
  { name: 'Laptop', label: 'Freelance / Tech', component: Laptop },
  { name: 'TrendingUp', label: 'Investments', component: TrendingUp },
  { name: 'Wallet', label: 'Allowance / Cash', component: Wallet },
  { name: 'Smartphone', label: 'Mobile & Internet', component: Smartphone },
  { name: 'Gift', label: 'Gifts & Donations', component: Gift },
  { name: 'PiggyBank', label: 'Savings', component: PiggyBank },
  { name: 'CreditCard', label: 'Credit Card', component: CreditCard },
  { name: 'Building', label: 'Business / Office', component: Building },
  { name: 'MoreHorizontal', label: 'Other', component: MoreHorizontal },
  { name: 'Tag', label: 'General', component: Tag },
];

export const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  Utensils,
  Car,
  ShoppingBag,
  GraduationCap,
  Film,
  Receipt,
  HeartPulse,
  Plane,
  Tv,
  MoreHorizontal,
  Briefcase,
  Laptop,
  TrendingUp,
  Wallet,
  PlusCircle,
  Coffee,
  Book,
  Home,
  Smartphone,
  Gift,
  PiggyBank,
  Fuel,
  Bus,
  Tag,
  CreditCard,
  Building,
  Sparkles,
  ShoppingBasket,
  Smile,
};

interface CategoryIconProps extends LucideProps {
  name: string;
}

export const CategoryIcon: React.FC<CategoryIconProps> = ({ name, ...props }) => {
  const IconComponent = ICON_MAP[name] || Tag;
  return <IconComponent {...props} />;
};
