export type TransactionType = 'expense' | 'income';

export type PaymentMethod = 
  | 'Cash' 
  | 'UPI' 
  | 'Debit Card' 
  | 'Credit Card' 
  | 'Bank Transfer' 
  | 'Other';

export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';

export interface RecurringSchedule {
  id: string;
  type: TransactionType;
  amount: number;
  category: string; // Category ID
  description: string;
  paymentMethod: PaymentMethod;
  notes?: string;
  frequency: RecurrenceFrequency;
  startDate: string; // YYYY-MM-DD
  nextDueDate: string; // YYYY-MM-DD
  endDate?: string; // Optional YYYY-MM-DD
  lastGeneratedDate?: string; // YYYY-MM-DD
  autoGenerate: boolean; // Auto-generate transaction when due
  status: 'active' | 'paused' | 'completed';
  createdAt: number;
}

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  category: string; // Category ID
  description: string;
  date: string; // YYYY-MM-DD
  paymentMethod: PaymentMethod;
  notes?: string;
  recurring?: 'none' | 'daily' | 'weekly' | 'monthly' | 'yearly';
  // Recurring extension fields
  isRecurring?: boolean;
  recurringScheduleId?: string; // Linked RecurringSchedule ID if scheduled or generated
  isAutoGenerated?: boolean; // True if automatically created by scheduler
  generationDate?: string; // Date/timestamp string when auto-generated
  createdAt: number;
}

export interface Category {
  id: string;
  name: string;
  type: TransactionType;
  icon: string; // Lucide icon key
  isCustom?: boolean;
  budgetLimit?: number;
}

export interface Budget {
  id: string;
  categoryId: string;
  monthlyLimit: number;
}

export interface UserSettings {
  currency: string;
  currencySymbol: string;
  theme: 'light' | 'dark' | 'system';
  dateFormat: 'DD/MM/YYYY' | 'MM/DD/YYYY' | 'YYYY-MM-DD';
  defaultTransactionType: TransactionType;
  firstDayOfWeek: 'monday' | 'sunday';
}

export type ActiveTab = 'overview' | 'transactions' | 'budgets' | 'categories' | 'reports' | 'settings';
